### ISSUE TITLE
Canonical form

### ISSUE THREAD

**Issue by Kubuxu** [multiformats/unsigned-varint#5]
Base 128 varints, aka Protobuf Varints, in theory can be expanded to more than one byte even if there is no need for it.
Example:
`0000 0001` is one
and
`1000 0000, 0000 0001` is also a one.

We should decide what to do with them, either allow them to be stored and used or just accept them but canonize them on a fly or just disallow them to prevent hash ambiguity.

**Comment by Kubuxu** [comment]
In my opinion it might be worth considering making them invalid and thus preventing their usage. As those varints won't be user input, it means that they can be created only by software and accepting those can lead to software that produces them even if they are discouraged.

**Comment by jbenet** [comment]
- protobuf varints are in wide use for cryptographic applications. so if the claim is that protobuf varints are inconsistent/unstable, then we should find out what other crypto systems using protobufs do.
- I believe all protobuf implementations default to the most compressed varint representation. meaning superfluous zeros are not _created_, though they can be read.
- There seem to be two claims: 
  - (a) "protobuf varint implementations read varints which may have superfluous leading zeros, which change the hash of an "otherwise-equal" value"
  - (b) "protobuf varint implementations write varints which may have superfluous leading zeros" (_i believe_ this is false).
- (b) would definitely be a problem, but i think it's false.
- I'm not sure (a) is a problem. 
- if we say (a) is a problem, im not sure what we would do with protobufs users have and want to extract _exactly the same_.

I do know that:

```go
o1 = <user-object>
d1 = protobuf.EncodeWithSuperfluousZeros(o1)
o2 = protobuf.Encode(d1)
d2 = protobuf.Decode(o2)

bytes.Equal(d2, d2) # may be false !!!
```
and this is definitely wonky. 

but i haven't thought through alternatives to know that similar _or worse_ wonkiness isn't to be found on the other end. have you? what makes you _absolutely certain_ that no edgecase wonkiness like this is at the other side?

**Comment by Kubuxu** [comment]
I haven't found any software currently that does the case (b) but it doesn't include a chance that someone creates some software. I am unsure about implications of something like that apart from infinity many addresses to exactly the same object, possible increased storage size if ever some software produces such address in link, as de-duplication of linking objects won't work.

**Comment by Kubuxu** [comment]
In the https://github.com/multiformats/multicodec/pull/16 @diasdavid wanted to define SHA1 as: `0b00010001` and udp as `0b10000000 00010001` which decode to the same value but would mean different things. This was IMO invalid use of varints and thus my concerns raised.

The issue itself isn't really about protobufs but varints inside multiformats suite.

**Comment by ivan386** [comment]
I changed varint in [golang/protobuf](https://github.com/ivan386/protobuf-1/commit/b76098a2adb7a080231cf14903ab7f3687667ce6) so now may not be the same values.

**Comment by jmitchell** [comment]
If different unsigned-varints can possibly decode to the same natural number, the specification should address how unsigned-varints are compared for equality. Without that, developers may be tempted to compare at the byte-level, and there could be multiple (and possibly conflicting) identifiers for the same thing.

A canonical encoding would make byte-level comparisons acceptable. To clarify what I (and I think @Kubuxu) mean by canonical encoding, given the functions

```
encode :: Nat -> [Byte]
decode :: [Byte] -> Nat
```

for all `Nat`s `n` it should be true that

```
decode (encode n) == n
```

However, some bytes may be invalid and not map to a `Nat`, e.g. `1 << 15`, so it wouldn't be the case that `encode (decode n) == n`.

> (a) "protobuf varint implementations read varints which may have superfluous leading zeros, which change the hash of an "otherwise-equal" value"
> ...
> if we say (a) is a problem, im not sure what we would do with protobufs users have and want to extract exactly the same.

Parsers tend to be flexible in what they consume, even accepting undesirable encodings. This strategy can be beneficial in situations where the intent of the encoded information won't be misconstrued. However, in this case where unsigned-varints are intended to be used to signify identity it's especially important to have a cohesive explicit strategy in the spec.

If undesirable unsigned-varint byte arrays (e.g. `1 << 15`) are accepted, their interpretation should be specified. Additionally, if we go this route it may be worth talking about supporting two separate multiformat hashing input strategies:

1. raw bytes (I'm fairly sure this is what's used now)
2. parsed AST, so inconsistencies like multiple distinct unsigned-varints decoding to the same identifier go away

**Comment by Stebalien** [comment]
This has been fixed.
